### ISSUE TITLE
react-application-messagebanner - 

### ISSUE THREAD

**Issue by vdykcj** [pnp/sp-dev-fx-extensions#1107]
### Sample

react-application-messagebanner

### Author(s)

@pmatthews05

### Question

Would it be possible to limit the users who see the message\banner via Audience Targeting, i.e. specific AD Groups and\or users? Any guidance or references would be appreciated.
![image](https://github.com/pnp/sp-dev-fx-extensions/assets/30402414/d5bf29e3-a590-4080-ba8a-9340c1baf19e)

**Comment by pmatthews05** [comment]
Hi @vdykcj,
 Thank you for your question. I've never done anything regarding Audience Targeting before, and to be honest, I haven't done much SPFX work since I submitted this. However, I have come across the following post by @rabwill.

**Blog:** https://rabiawilliams.com/spfx/spfx-react-targetaudience/ 
**git-repo:** https://github.com/rabwill/generic-target-audience

This blob post and GitHub repo looks like you could incorporate into the react-application-messagebanner and wrap the component around the banner.
