### ISSUE TITLE
How to Set Possition of Command button

### ISSUE THREAD

**Issue by enti333** [pnp/sp-dev-fx-extensions#209]
- [x] Question
- [ ] Bug
- [x] Enhancement

Hello. I want to ask if is possible to set position of my new command button. 
I have created extension command button...My button is always on end...I need to set it to first position in command bar. Is this possible?
Also Is possible to register custom command button on contenttype?Like on old ribbon:
RegistrationType="ContentType"
RegistrationId="0x01"

Thank you

**Comment by sudharsank** [comment]
Hi @enti333 
I don't think so that you can position the command button, since there is no property available to set it via the '**elements.xml**' or '**clientsideinstance.xml**'. 
Regarding the display of the button based on the content type, you can look for the item details that is returned whenever an item is selected, based on the content type information you can display or hide the button as you like.

**Comment by enti333** [comment]
Yes you are right. But I think that this is a base functionallity which is missing. Thank you
