### ISSUE TITLE
react-application-machine-translations - Get entire page text?

### ISSUE THREAD

**Issue by lrolseth** [pnp/sp-dev-fx-extensions#320]
react-application-machine-translations

Question: Do you know how to get the entire page text of a modern SharePoint site to translate?  
I have this example running successfully and it pulls the ClientsideText controls on the page.  I'd like to pull all text that is displayed on the page and translate it. Is this possible?

**Comment by hugoabernier** [comment]
@lrolseth did you ever get a resolution to this issue?

I'll go ahead and close the issue. If you'd still like help with this, please don't hesitate to open a new issue. When you do, please take the time to fill the issue template with all the required sections so that we can help you better,

Keep in mind that authors are not automatically notified unless you fill the template completely.

Thanks for your understanding!
