### ISSUE TITLE
Lodash-2.4.2.js version vulnerabilities in SPFX while using White source Bolt in CI/CD Pipeline.

### ISSUE THREAD

**Issue by AJAYSIRANGI27** [pnp/sp-dev-fx-extensions#326]
Hi All,

i am developing solutions for SharePoint Server 2019 or SharePoint Online in refer to https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/react-aadtokenprovider-bot

When i tried to create a CI/CD pipeline for the solution with following versions of node  and  npm.

_versions_
Node--10.x
npm-6.14.4

_Commands_
npm install
gulp clean
gulp build
gulp bundle --ship
gulp package-solution --ship

am getting  few vulnerabilities in lodash
![Screenshot (302)](https://user-images.githubusercontent.com/62381755/87901493-d19d8580-ca74-11ea-80c3-131fbebd7c4c.png)
h

  | Versions of lodash lower than 4.17.12 are vulnerable to Prototype Pollution.
-- | --

  | Versions of lodash lower than 4.17.12 are vulnerable to Prototype Pollution.
-- | --

I tried Updating lodash using **npm install lodash@latest**, But nothing helped.

Can someone please help me on this.

**Comment by naveenwinsome** [comment]
Hi,

Just to add what @AJAYSIRANGI27 has mentioned. We are using this solution to deliver SPFX Chatbot on Modern SharePoint to a U.S Govt agency. We have also got into some GPL 2.0 license issues with the solution. It would be really helpful if you can provide a direction.

![gpl2 0](https://user-images.githubusercontent.com/8735346/87907129-a2414580-ca81-11ea-96bc-21fa8208057a.png)

![gpl2 0_1](https://user-images.githubusercontent.com/8735346/87907152-ab321700-ca81-11ea-8569-51be36307d30.png)



Thanks,
Naveen

**Comment by hugoabernier** [comment]
@AJAYSIRANGI27 the sample you are referring to was written in 2018. At the time it was published, it was reviewed for potential exploits. 

Packages are constantly scanned for exploits and vulnerabilities; a solution that may not have any discovered vulnerabilities in 2018 may no longer be considered safe.

You should always ensure to review and update your solutions (especially open-source ones) before you use them in your environment. I would recommend that you always upgrade the associated modules for safety reasons. Keep in mind that some of these updates may break compatibility with dependencies.

Ultimately, it is up to you (and your organization) to determine whether a solution is acceptable for your environment. The samples in this repository are only intended to be used as samples to demonstrate a feature or an approach using application extensions.

We always encourage members of the community to contribute and improve samples. If you update the solution to a version that shows fewer detected vulnerabilities, please do not hesitate to share with everyone. 

Thanks for your concerns, and feel free to share your results so that others can benefit from them.
