### ISSUE TITLE
Critical issue - SP Online some standard command buttons does not work when ListViewCommandSet is installed

### ISSUE THREAD

**Issue by honb** [pnp/sp-dev-fx-extensions#328]
- Tried to run "**react-command-direct-link**" at local page by adding "**?debugManifestsFile=....**" params
- Or install ListViewCommandSet in app catalog

If command bar button is visible then Delete button will not work.
Tested with Document Library view "Shared Documents/Forms/AllItems.aspx", there is a custom command bar that always visible then "**Create new folder**" and "**Delete**" button does not work.

Removed the app from catalog then all standard commands work well.

**Comment by hugoabernier** [comment]
Thanks for reporting the issue,  @honb , but we can't help you if you don't provide us with all the information we request in the issue template. 

I'll mark the issue as closed, but please feel free to create a new issue and provide all the details from the issue template so that we can help you accordingly. 

Thanks for your understanding
