### ISSUE TITLE
Sample Request: App Customizer to inject Custom CSS onto Modern UI pages for 2019 On-Prem

### ISSUE THREAD

**Issue by hugoabernier** [pnp/sp-dev-fx-extensions#357]
I would like to use App Customizer to inject Custom CSS onto Modern UI pages. I referenced [this](https://github.com/pnp/sp-dev-fx-extensions/tree/master/samples/react-application-injectcss) code to try to make it work on 2019 On-Prem, but ran into many issues. 

Any help with the code or guidance would be greatly appreciated.

_Originally posted by @amalwayscharan in https://github.com/pnp/sp-dev-fx-extensions/discussions/356_

**Comment by sudharsank** [comment]
Hi @amalwayscharan,
I tried the same code with the new project created by choosing SP2019 onwards and SharePoint Online and it works like charm. I haven't done any changes. Following are the files that are copied from the original code. There are couple of warnings because of tslint but it works. Please try it out and let us know the errors if any.

- InjectCssApplicationCustomizer.ts
- ClientSideInstance.xml
- elements.xml
- serve.json (to redirect to my sharepoint site url)
