### ISSUE TITLE
react-command-file-size-viewer

### ISSUE THREAD

**Issue by Ramiz-Arshad** [pnp/sp-dev-fx-extensions#359]
react-command-file-size-viewer.

Hi @jquintozamora ,

I cloned the repository react-command-file-size-viewer and followed the steps mentioned in the repository. When I am running gulp serve -- no browser and adding the url at the end of my document library
**?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js&customActions={"5f509a36-9998-4a5f-a5f4-b7d02d4f90b4":{"location":"ClientSideExtension.ListViewCommandSet"}}**

I am facing the error 
![image](https://user-images.githubusercontent.com/28856501/107510945-dadb7480-6bb5-11eb-84eb-aa93281cd9d3.png)

I tried checking the server.json file but couldnt get it so far. Can anyone check whether this solution is working or not?

Regards
Ramiz

**Comment by hugoabernier** [comment]
@Ramiz-Arshad, we'd love to help you, but in order to do so, we'll need you to fill the bug issue template that's provided -- the one we ask for your environment details, author details, etc.

I'll go ahead and close this issue as incomplete. Feel free to open a new issue so that we can get you the help you deserve.

Thanks for your understanding.
