### ISSUE TITLE
react-application-my-lists-notifications - 

### ISSUE THREAD

**Issue by zenaidura** [pnp/sp-dev-fx-extensions#411]
### Sample

react-application-my-lists-notifications

### Author(s)

@joaojmendes

### Question

Its great work and highly usable however my client is also interested to show same notifications when a comment is added to a site page.
Currently I have a solution that crawls through all site pages and using REST APIs, capture the comments, likes and replies for each page and creates an entry in the Activity list. You used subscription to changes, does it trigger if the comment is added as well? if not than do you have any other solution for my client?

**Comment by mohammadamer** [comment]
Hi @zenaidura 

Have you though about **SharePoint Webhook** instead of crawling through all site pages. I think page comment or page like is item change and SharePoint Webhook will be trigger on item change.
You can receive changes through the Webhook notification that will be trigger on item change.

I didn't try webhook on item comments or likes but I tried it on the properties changes.

**Comment by zenaidura** [comment]
Yes please close it

Ashar Khan

LinkedIn: http://linkedin.com/in/ashar
Website: http://www.ashark.net
